# Galax for Alacritty
# ~/.config/alacritty/theme.toml

[colors.cursor]
cursor = "#dcd5ac"
text = "#181820"

[colors.footer_bar]
background = "#d5cea3"
foreground = "#16161d"

[colors.hints.end]
background = "#16161d"
foreground = "#dcd5ac"

[colors.hints.start]
background = "#dcd5ac"
foreground = "#16161d"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.bright]
black = "#7e7d74"
blue = "#92abde"
cyan = "#89bfaa"
green = "#c2dd96"
magenta = "#da97ad"
red = "#e8808b"
white = "#e5ddb0"
yellow = "#ebce9c"

[colors.normal]
black = "#53524c"
blue = "#7e9cd8"
cyan = "#6caf95"
green = "#b3d57d"
magenta = "#d27e99"
red = "#e46876"
white = "#dcd5ac"
yellow = "#e6c384"

[colors.primary]
background = "#16161d"
bright_foreground = "#e5ddb0"
dim_foreground = "#d5cea3"
foreground = "#dcd5ac"

[colors.search.focused_match]
background = "#b3d57d"
foreground = "#181820"

[colors.search.matches]
background = "#7e9cd8"
foreground = "#181820"

[colors.selection]
background = "#1a1a22"
text = "#dcd5ac"

[colors.vi_mode_cursor]
cursor = "#dcd5ac"
text = "#181820"
    