#!/usr/bin/env bash

source ./scriptdata/functions.sh

# Install basic packages
sudo pacman -S --noconfirm --needed base-devel git fish

if ! check_dep paru; then
  sudo pacman -S --noconfirm --needed rustup

  # Install rustup toolchain
  rustup install stable
  rustup default stable

  sleep 1

  # Install Paru
  git clone https://aur.archlinux.org/paru.git
  pushd paru
  makepkg -si --noconfirm
  popd
  rm -rf paru
fi

paru -Syy --noconfirm
paru -Sy --noconfirm archlinux-keyring
paru -S --noconfirm --needed - <./scriptdata/pkgs.txt

sudo systemctl enable sddm.service

xdg-user-dirs-update

# Fonts
rm -rf ~/.local/share/{themes,fonts}
mkdir -p ~/.local/share/{themes,fonts}
cp -R ./fonts/{AstroNerdFont,MaterialIcons,NotoColorEmoji-Regular.ttf} ~/.local/share/fonts/
sudo cp -R ./fonts/OpenSans /usr/share/fonts/
fc-cache -r

# Wallpapers
sudo cp config/awesome/theme/assets/greeting.png /usr/share/sddm/themes/Sugar-Candy/Backgrounds/

# Install GTK themes
cp -R ./theme/gtk/{Interstellar,Interstellar-Darker} ~/.local/share/themes/

# Backup old configs
mv ~/.config ~/.config.backup
ln -s ~/.dots/config ~/.config
# Copy common system configs
sudo cp -R ./settings/xorg.conf.d /etc/X11/
sudo cp -R ./settings/sddm.conf.d /etc/
sudo cp ./config/sugar-candy/theme.conf /usr/share/sddm/themes/Sugar-Candy/
cp ./settings/{.gitconfig,.xprofile} ~/
cp -R ./settings/.icons ~/

# Remove default cursor theme
sudo rm -rf /usr/share/icons/default

# pnpm
if ! check_dep pnpm; then
  curl -fsSL https://get.pnpm.io/install.sh | sh -
fi

# Run Docker with current user privileges
sudo usermod -aG docker $USER

paru -Rns $(paru -Qdtq)
paru -Scc --noconfirm

echo "\nReboot to your system and Happy coding!"
